WITH temp_oa_joined_cleaned1 AS 
(
SELECT * FROM temp_oa_joined_cleaned
--WHERE RATE_USD IS NOT NULL
),

all_zipcoords AS
(
SELECT OA0.ORIGIN_3DIGIT_ZIP AS ZIP, 
OA0.X_COORD_ORIG AS X_COORD, OA0.Y_COORD_ORIG AS Y_COORD
{% if add_features_for_visuals_map_zips == 1 %}
, OA0.RATE_USD
{% endif %}
FROM temp_oa_joined_cleaned1 OA0
UNION ALL
SELECT OA1.DESTINATION_3DIGIT_ZIP AS ZIP, 
OA1.X_COORD_DEST AS X_COORD, OA1.Y_COORD_DEST AS Y_COORD
{% if add_features_for_visuals_map_zips == 1 %}
, OA1.RATE_USD
{% endif %}
FROM temp_oa_joined_cleaned1 OA1
),

zipcode_groupby AS
(
SELECT AZC0.ZIP, AZC0.X_COORD, AZC0.Y_COORD,
LN(COUNT(*)+1)/10 AS ZIP_OFFER_NUM_SCALED,
{% if add_features_for_visuals_map_zips == 1 %}
COUNT(*) AS ZIP_OFFER_NUM, 
AVG(LN(AZC0.RATE_USD+1)) AS ZIP_RATE_AVG
{% endif %}
FROM
all_zipcoords AZC0
GROUP BY AZC0.ZIP, AZC0.X_COORD, AZC0.Y_COORD
),

all_zipcoords_orders_level AS
(
SELECT OA0.ORIGIN_3DIGIT_ZIP AS ZIP, 
OA0.X_COORD_ORIG AS X_COORD, OA0.Y_COORD_ORIG AS Y_COORD
, OA0.ORDER_OFFER_AMOUNT
FROM oa OA0
UNION ALL
SELECT OA1.DESTINATION_3DIGIT_ZIP AS ZIP, 
OA1.X_COORD_DEST AS X_COORD, OA1.Y_COORD_DEST AS Y_COORD
, OA1.ORDER_OFFER_AMOUNT
FROM oa OA1
),

zipcode_groupby_orders_level AS
(
SELECT
AZCOL0.ZIP, AZCOL0.X_COORD, AZCOL0.Y_COORD
, AVG(AZCOL0.ORDER_OFFER_AMOUNT) AS ZIP_ORDER_OFFER_AMOUNT_AVG
FROM
all_zipcoords_orders_level AZCOL0
GROUP BY AZCOL0.ZIP, AZCOL0.X_COORD, AZCOL0.Y_COORD
)

SELECT 
ZCGB0.ZIP, ZCGB0.X_COORD, ZCGB0.Y_COORD, 
ZCGB0.ZIP_OFFER_NUM_SCALED
{% if add_features_for_visuals_map_zips == 1 %}
,
ZCGB0.ZIP_OFFER_NUM, 
ZCGB0.ZIP_RATE_AVG,
NTILE(3) OVER (ORDER BY ZCGB0.ZIP_RATE_AVG DESC) AS ZIP_RATE_AVG_LVL,
ZCGB1.ZIP_ORDER_OFFER_AMOUNT_AVG,
NTILE(3) OVER (ORDER BY ZCGB1.ZIP_ORDER_OFFER_AMOUNT_AVG DESC) AS ZIP_ORDER_OFFER_AMOUNT_AVG_LVL
{% endif %}

FROM
zipcode_groupby ZCGB0
INNER JOIN 
zipcode_groupby_orders_level ZCGB1
ON ZCGB0.ZIP = ZCGB1.ZIP




