analysis-paths:
- analyses
clean-targets:
- target
- dbt_packages
config-version: 2
macro-paths:
- macros
model-paths:
- models
models:
  tempsample:
    example:
      +materialized: view
name: dbtflock
profile: default
seed-paths:
- seeds
snapshot-paths:
- snapshots
test-paths:
- tests
vars:
  add_features_for_visuals_map_zips: 0
  dont_explode_references: 0
  filtering_ftl: 0
version: 1.0.0
